name: Chzzk Category Tracker

on:
  schedule:
    - cron: '*/5 * * * *' # 5분마다 실행
  workflow_dispatch:      # 수동으로도 실행 가능하게 함

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: 파이썬 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 라이브러리 설치
        run: pip install requests gspread oauth2client

      - name: 트래커 실행
        env:
          GOOGLE_SHEET_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_CREDENTIALS }}
        run: python tracker.py
